### ISSUE TITLE
1.21 Dev version "Unknown Material Scute"

### ISSUE THREAD

**Issue by LUF3N** [VolmitDev/Iris#2]
### Problem

While using the world updater i got the following notification.
I am not sure if its a bug or maybe a wrong named material.
Thought better be safe than sorry :P

![scute](https://github.com/VolmitDev/Iris/assets/33790183/417994c3-90ec-47ac-ba23-a3596d4b88ea)

### Minecraft Version

1.21

### Iris Version

v3.3.1-1.19.2-1.20.6

### Log

https://paste.myplayplanet.tools/ejimorexiw.md

**Comment by CrazyDev05** [comment]
That's a bug with the gen itself
