### ISSUE TITLE
1.21 Dev version "failed to set entity data"

### ISSUE THREAD

**Issue by LUF3N** [VolmitDev/Iris#3]
### Problem

While using the world updater i got the following notification.
Not sure if its a bug.
![entitydata](https://github.com/VolmitDev/Iris/assets/33790183/2aa7cf1e-058c-419b-8ab5-639179de7dd0)

### Minecraft Version

1.21

### Iris Version

v3.3.1-1.19.2-1.20.6

### Log

https://paste.myplayplanet.tools/ejimorexiw.md

**Comment by CrazyDev05** [comment]
That's a bug with the gen itself
